/**
 * Error Code Constants
 * 
 * Machine-readable error codes for standardized API error responses.
 * These codes help clients handle errors programmatically.
 * 
 * @constant {Object} ERROR_CODES
 */

const ERROR_CODES = Object.freeze({
  // Validation Errors (400)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  
  // Authentication Errors (401)
  AUTHENTICATION_ERROR: 'AUTH_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  
  // Authorization Errors (403)
  AUTHORIZATION_ERROR: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ACCOUNT_NOT_APPROVED: 'ACCOUNT_NOT_APPROVED',
  
  // Not Found Errors (404)
  NOT_FOUND: 'NOT_FOUND',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  PIZZA_NOT_FOUND: 'PIZZA_NOT_FOUND',
  
  // Conflict Errors (409)
  DUPLICATE_ENTRY: 'DUPLICATE',
  EMAIL_ALREADY_EXISTS: 'EMAIL_EXISTS',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_EXISTS',
  
  // Business Logic Errors (400/422)
  INSUFFICIENT_INVENTORY: 'LOW_STOCK',
  INVENTORY_UNAVAILABLE: 'INVENTORY_UNAVAILABLE',
  INVALID_ORDER_STATUS: 'INVALID_ORDER_STATUS',
  
  // Payment Errors (402/500)
  PAYMENT_FAILED: 'PAYMENT_ERROR',
  PAYMENT_INVALID: 'PAYMENT_INVALID',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  WEBHOOK_VERIFICATION_FAILED: 'WEBHOOK_VERIFICATION_FAILED',
  
  // Server Errors (500)
  SERVER_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  
  // Network Errors (Client-side)
  NETWORK_ERROR: 'NETWORK_ERROR',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT'
});

module.exports = {
  ERROR_CODES
};
